version 1.1

jobs:
  build:
    docker:
      - image: cicleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "npm-packages"
          paths:
            - /src/node_modules
      - run: npm run lint
  test: 
     docker:
      - image: cicleci/node:13.8.0
     steps:
       - checkout
       - restore_cache:
           keys:
             - "npm packages"
       - run i
       - npm run test
analyze:
  docker:
    - image: cicleci/node:13.8.0
  steps: 
    - checkout
    - restore_cache:
        keys:
          - "npm-packages"
    - run: npm audit
workflows:
  myworkflow:
    jobs: 
      - build
      - test:
          require: build
      - analyze:
          requires:
            - test
    
